apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "gostint.fullname" . }}
  labels:
    app: {{ template "gostint.name" . }}
    chart: {{ template "gostint.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "gostint.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "gostint.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: GOSTINT_DBURL
              value: {{ template "mongodb.fullname" . }}:27017
            - name: VAULT_ADDR
              value: http://{{ template "vault.fullname" . }}:8200
              # TODO: https
            - name: GOSTINT_DBAUTH_TOKEN
              value: TODO
            - name: GOSTINT_ROLEID
              value: TODO
          # TODO: Priviledge for DND
          securityContext:
            privileged: true
            # readOnlyRootFilesystem: true
            # capabilities:
            #   add:
            #   -
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        # - name: {{ template "gostint.fullname" . }}
        #   secret:
        #     tlsKey: todo
        #     tlsCert: todo
