{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  name: {{ template "gostint.fullname" . }}-ingress
  labels:
    app: {{ template "gostint.name" . }}
    chart: {{ template "gostint.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
    - http:
        paths:
          - path: /vault
            backend:
              serviceName: {{ template "gostint.fullname" . }}-vault
              servicePort: 8200
          - path: /gostint
            backend:
              serviceName: {{ template "gostint.fullname" . }}
              servicePort: 3232
  tls:
    - secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}
