apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: {{ template "gostint.fullname" . }}-ingress
  labels:
    app: {{ template "gostint.name" . }}
    chart: {{ template "gostint.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  # namespace: foo
spec:
  rules:
    - http:
        paths:
          - path: /vault
            backend:
              serviceName: {{ template "gostint.fullname" . }}-vault
              servicePort: 8200
          - path: /gostint
            backend:
              serviceName: {{ template "gostint.fullname" . }}
              servicePort: 3232
  # This section is only required if TLS is to be enabled for the Ingress
  tls:
    - secretName: aut-op-ingress-tls
