apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gostint.fullname" . }}-vault-config
  labels:
    app: {{ template "gostint.name" . }}
    chart: {{ template "gostint.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  vault.hcl: |
    ui = true
